import Foundation

/// Журнал изменений для пользователя («Что нового»). Дописывать сверху при заметных правках.
/// Кратко, в нашем тоне — не дев-журнал (тот в docs/JOURNAL.md).
enum Changelog {
    struct Release { let version: String; let ru: [String]; let en: [String] }

    static let releases: [Release] = [
        Release(version: "0.2.12",
            ru: ["Обновления переехали в отдельный раздел настроек «Обновления» — раньше прятались в «Общих», их не находили. И логичнее: «Ставить сразу без вопросов» теперь сам включает «Проверять обновления» и блокирует его (без проверки тихая установка невозможна).",
                 "Чиним слова, набранные с концевой буквой б/ю/ж: «yj;» → «нож» (раньше выходило «но;» — терялась буква), «[kt,» → «хлеб».",
                 "Чиним слова с цифрой на конце: «ghbdtn2» → «привет2». Короткие технические токены (gj1, h2o) не трогаем."],
            en: ["Updates moved to their own “Updates” settings section — they used to hide under “General” and people couldn't find them. Also smarter: “Install right away” now turns on “Check for updates” and locks it (silent install is impossible without checking).",
                 "Words ending in б/ю/ж now fix correctly: “yj;” → “нож” (was “но;”, a lost letter), “[kt,” → “хлеб”.",
                 "Words with a trailing digit get fixed: “ghbdtn2” → “привет2”. Short technical tokens (gj1, h2o) are left alone."]),
        Release(version: "0.2.11",
            ru: ["В меню у часов появился пункт «Проверить обновления…» — удобно глянуть свежую версию вручную."],
            en: ["The menu by the clock now has a “Check for Updates…” item — handy to look for a fresh version manually."]),
        Release(version: "0.2.10",
            ru: ["Чиним слова со скобкой/кавычкой/тире перед ними: «(tckb» теперь превращается в «(если», а раньше упрямо оставалось как есть. Раньше любой символ перед словом (скобка, кавычка, дефис) ломал распознавание целиком."],
            en: ["Words with a bracket/quote/dash stuck to them now get fixed: \"(tckb\" turns into \"(если\" — before, any character in front of a word (bracket, quote, dash) broke detection entirely."]),
        Release(version: "0.2.9",
            ru: ["Главное: авто-переключение стало НАДЁЖНЫМ при быстром сплошном наборе. Раньше при печати без пауз часть слов чинилась, часть нет, а иногда первые буквы оставались в старой раскладке («gпривет»). Причина — приложение путало собственные нажатия с твоими по таймеру; теперь оно метит свой ввод и не теряет ни одной твоей буквы.",
                 "Стыдный недосмотр: у новых пользователей авто-переключение было выключено из коробки. Теперь включено по умолчанию.",
                 "Enter теперь тоже чинит слово — «ghbdtn» + Enter в чате превратится в «привет» перед отправкой."],
            en: ["Big one: automatic switching is now RELIABLE when you type fast and continuously. Before, some words got fixed and some didn't, and sometimes the first letters stayed in the wrong layout (\"gпривет\"). The cause: the app told its own keystrokes from yours by timing; now it tags its own input and never drops a letter of yours.",
                 "An embarrassing oversight: for new users, auto-switching was off out of the box. It's on by default now.",
                 "Enter now fixes the word too — \"ghbdtn\" + Enter in a chat becomes \"привет\" before it sends."]),
        Release(version: "0.2.8",
            ru: ["Знакомство теперь открывается заставкой во весь экран: на тёмном фоне K собирается из чертежа, затем плавно растворяется — и появляется приветствие. Коротко, один раз, без звука.",
                 "Пересмотреть можно когда угодно — пункт «Знакомство…» в меню у часов."],
            en: ["The intro now opens full-window: on a dark backdrop the K assembles itself from a blueprint, then gently dissolves into the welcome screen. Short, once, silent.",
                 "Revisit it anytime — “Welcome…” in the menu by the clock."]),
        Release(version: "0.2.6",
            ru: ["Баннер обновления довели до ума: крупный логотип, ровные поля со всех сторон, а коралловая кнопка «Обновить сейчас» теперь надёжно заметна в любом окружении (раньше в живом окне могла тускнеть до серой)."],
            en: ["The update banner is properly polished now: a larger logo, even padding all around, and the coral “Update now” button is reliably vivid everywhere (it could dim to grey in the live window before)."]),
        Release(version: "0.2.5",
            ru: ["Маленькая пасхалка в тему: теперь Keyboop находится в Spotlight, даже если набрать его имя вслепую на русской раскладке — «лунищщз». А ещё по «punto», «раскладка», «switcher»."],
            en: ["A fitting little easter egg: Keyboop now turns up in Spotlight even if you type its name in the wrong layout — “лунищщз”. Also by “punto”, “switcher”."]),
        Release(version: "0.2.4",
            ru: ["Баннер обновления стал аккуратнее: тёмный фон, кнопка «Обновить сейчас» теперь коралловая и заметная, больше воздуха, текст короче."],
            en: ["The update banner is tidier now: dark background, a clear coral “Update now” button, more breathing room, shorter text."]),
        Release(version: "0.2.3",
            ru: ["Песочница в окне знакомства теперь на две строки — удобнее попробовать целую фразу.",
                 "Высоту окна знакомства можно менять под себя."],
            en: ["The sandbox in the welcome window is now two lines — handier for trying a whole phrase.",
                 "The welcome window height is now resizable."]),
        Release(version: "0.2.2",
            ru: ["Про обновление теперь спрашивает наш собственный аккуратный баннер у часов («Обновить сейчас» / «Обновлять автоматически») — вместо системного уведомления. Никаких лишних разрешений на уведомления."],
            en: ["The \"update ready\" prompt is now our own tidy banner near the clock (\"Update now\" / \"Update automatically\") instead of a system notification. No extra notification permissions."]),
        Release(version: "0.2.1",
            ru: ["Причесали подзаголовки в настройках и окне знакомства — читаемые, ровные, в фирменном коралловом стиле (раньше были мелкие, серые и с кривым отступом).",
                 "В окне знакомства разъехались слипшиеся ряды выбора горячих клавиш — стало просторнее."],
            en: ["Tidied up section headers in Settings and the welcome window — readable, aligned, in the coral brand style (they used to be tiny, grey and oddly indented).",
                 "Welcome-window hotkey rows are no longer cramped — more breathing room."]),
        Release(version: "0.2.0",
            ru: ["Keyboop теперь сам находит новые версии. Когда выйдет новая — покажет уведомление с кнопкой «Обновить сейчас». Надоест нажимать каждый раз — там же кнопка «Обновлять автоматически»: дальше ставим тихо, в простое, когда ты отошёл, не мешая. Всё настраивается/выключается в Настройках → Обновления.",
                 "Обновления подписаны и проверяются — подсунуть поддельную сборку под видом апдейта не выйдет. Проверка «есть ли новее?» отправляет только твой IP и номер версии, как любой заход на сайт. Ничего из того, что ты печатаешь или диктуешь."],
            en: ["Keyboop now finds new versions on its own. When one ships, it shows a notification with an \"Update now\" button. Tired of clicking each time? There's an \"Update automatically\" button right there — after that we install quietly while you're away. All configurable in Settings → Updates.",
                 "Updates are signed and verified — no one can slip you a fake build disguised as an update. The \"is there a newer one?\" check sends only your IP and version number, like any website visit. Nothing you type or dictate."]),
        Release(version: "0.1.75",
            ru: ["Хоткей диктовки по умолчанию теперь — правый ⌥: зажал, говоришь, отпустил. Его (как и хоткей раскладки) можно поменять прямо в окне знакомства или в настройках.",
                 "Доступ к раскладке подхватывается на лету: выдал «Универсальный доступ» — переключение включается сразу, перезапуск не нужен. А если Keyboop запущен из образа или Загрузок — подскажем перетащить его в «Программы».",
                 "Модели распознавания — теперь в одном списке: любую можно скачать, активировать и удалить, чтобы не занимала место (переключатель Whisper/Parakeet убрали — меньше путаницы).",
                 "Хоткей перевода теперь тоже меняется в настройках."],
            en: ["Default dictation hotkey is now the right ⌥: hold, speak, release. It (and the layout hotkey) can be changed right in the welcome window or in settings.",
                 "Accessibility is picked up on the fly: grant it and switching turns on immediately — no restart. And if Keyboop is running from the disk image or Downloads, we'll nudge you to move it into Applications.",
                 "Recognition models are now in a single list: download, activate, or delete any of them to free up space (the Whisper/Parakeet switch is gone — less confusion).",
                 "The translation hotkey is now editable in settings too."]),
        Release(version: "0.1.59",
            ru: ["Предлоги-буквы теперь чинятся даже после английского слова: «room d новой» → «room в новой».",
                 "Но английские маркеры бережём по контексту: «vitamin d», «plan b», «gen z», «type o» остаются целыми.",
                 "Выбор движка распознавания: статус «используется» теперь стоит прямо напротив активной модели — и у Whisper, и у Parakeet.",
                 "Подсказки в настройках всплывают только у длинных подписей, которые не умещаются."],
            en: ["Letter-prepositions now get fixed even after an English word where they should.",
                 "But English markers are preserved by context: “vitamin d”, “plan b”, “gen z”, “type o” stay intact.",
                 "Recognition engine picker: the “in use” status now sits right next to the active model — for both Whisper and Parakeet.",
                 "Settings hints now appear only for long captions that don't fit."]),
        Release(version: "0.1.56",
            ru: ["Режим для разработчиков стал умнее: одиночные буквы и короткие сочетания (переменные, команды) не переключаются нигде — не только в IDE. Подпись в настройках теперь об этом говорит.",
                 "Без него предлоги-буквы чинятся как обычно: «d» → «в», «z» → «я» — кроме английского контекста («vitamin d» цел)."],
            en: ["Developer mode got smarter: single letters and short combos (variables, commands) are left alone everywhere — not just in IDEs. The settings caption now says so.",
                 "Without it, letter-prepositions are fixed as usual: “d” → “в” — except in English context (“vitamin d” stays intact)."]),
        Release(version: "0.1.55",
            ru: ["Детектор поумнел на коротких словах: смотрит на язык предыдущего слова. «привет yt» → «привет не», а «смотрю tv» и «Спартак vs Зенит» не трогает.",
                 "Одиночная «c» в английском тексте больше не превращается в «с»."],
            en: ["Smarter short-word detection: the previous word's language is taken into account. Mixed-in English tokens like “tv” or “vs” are left alone.",
                 "A lone “c” in English text no longer turns into “с”."]),
        Release(version: "0.1.54",
            ru: ["Длинные подсказки в настройках больше не теряются: текст усечён, а полный — во всплывающей подсказке (появляется почти сразу)."],
            en: ["Long hints in settings no longer get lost: text is trimmed, the full version shows in a tooltip (appears almost instantly)."]),
        Release(version: "0.1.53",
            ru: ["Переключение нескольких слов сразу одним хоткеем — теперь в основных настройках, сразу после ручного хоткея. Недоступно при авто-переключении, чтобы не конфликтовать. Под капотом — защита от порчи текста.",
                 "Свой звук для перевода: можно выбрать наш, системный или выключить, и настроить громкость.",
                 "Точнее с короткими словами: «c» → «с». «net» больше не трогаем — это английское слово, а не «нет».",
                 "История диктовок корректно переносится со старых версий."],
            en: ["Convert several words at once with one hotkey — now in the main settings, right after the manual hotkey. Disabled while auto-switch is on so they don't clash. Under the hood — guards against text corruption.",
                 "A dedicated translation sound: pick ours, a system one, or off, and set its volume.",
                 "Smarter on short words: “c” → “с”. “net” is left alone now — it's the English word, not “нет”.",
                 "Dictation history migrates correctly from older versions."]),
        Release(version: "0.1.52",
            ru: ["Выбор микрофона — прямо в настройках голосового набора.",
                 "Автозамена: кнопка-корзина у каждой строки, кнопка «Добавить» для удобства.",
                 "Исключения: кнопка «Добавить слово» переводит фокус на поле ввода.",
                 "История хранится в минутах (30 мин / 1 ч / 2 ч / 4 ч / 8 ч).",
                 "«с» и «tot» теперь корректно переключаются на русский."],
            en: ["Microphone selector — right in Voice settings.",
                 "Snippets: per-row trash button, Add button for convenience.",
                 "Exceptions: Add Word button focuses the input field.",
                 "History retention in minutes (30 min / 1 h / 2 h / 4 h / 8 h).",
                 "\"с\" and \"tot\" now correctly switch to Russian."]),
        Release(version: "0.1.18",
            ru: ["Длинная диктовка больше не теряет хвост — распознаётся целиком.",
                 "Под капотом подготовлен новый движок распознавания Parakeet (точнее на русском) — скоро."],
            en: ["Long dictation no longer drops the tail — it’s transcribed in full.",
                 "Groundwork for a new recognition engine, Parakeet (better Russian) — coming soon."]),
        Release(version: "0.1.15",
            ru: ["История диктовок: живое обновление, прокрутка к последней, настраиваемая прозрачность окна.",
                 "Срок хранения истории — на выбор (3 / 7 / 30 дней)."],
            en: ["Dictation history: live updates, scroll-to-latest, adjustable window translucency.",
                 "History retention is configurable (3 / 7 / 30 days)."]),
        Release(version: "0.1.12",
            ru: ["После голосового ввода ставится пробел — следующая фраза не слипается.",
                 "Отдельные настройки звука записи: вкл/выкл и громкость."],
            en: ["A space is added after dictation — the next phrase won’t stick together.",
                 "Separate recording-sound settings: toggle and volume."]),
        Release(version: "0.1.9",
            ru: ["Свои звуки старта/окончания записи.",
                 "В «О программе» — кнопка обратной связи и подписка на обновления (почта + Telegram)."],
            en: ["Custom start/stop recording sounds.",
                 "In About — a feedback button and update subscription (email + Telegram)."]),
        Release(version: "0.1.8",
            ru: ["Умнее с раскладкой: не переключаем короткие «не-слова» (например «тк»), добавлены русские сокращения."],
            en: ["Smarter layout handling: short non-words (like “тк”) aren’t switched; Russian abbreviations added."]),
        Release(version: "0.1.2",
            ru: ["Хоткей диктовки по умолчанию — ⌥` , режим «нажал-старт / нажал-стоп».",
                 "Доступ к микрофону спрашивается сам; автозапуск при входе включён."],
            en: ["Default dictation hotkey is ⌥`, toggle mode (press-start / press-stop).",
                 "Microphone access is requested automatically; launch-at-login is on."]),
    ]
}
